### ISSUE TITLE
Search text?

### ISSUE THREAD

**Issue by MRM-Oly** [amandavisconti/infinite-ulysses-dissertation#96]
I may have missed it, but is there a way to search the text?  If not, that's something that would be useful to me.
Congratulations on defending your dissertation

**Comment by amandavisconti** [comment]
Thanks! There isn't currently a search function, but I'd like to have that up for the 1.0 release this June. If there are any particular ways you'd like search to work (e.g. limit search to book text, annotation text, etc.), let me know!

**Comment by amandavisconti** [comment]
Moving to amandavisconti/infinite-ulysses-public's #2.

**Comment by MRM-Oly** [comment]
Sorry - just realized I didn't get back to you. I'm interested in searching
the text, mostly.

Thanks
Manek
